name: CI-CD-Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  build-test-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      # ------------------------
      # 1?? Unit Tests
      # ------------------------
      - name: Run Unit Tests
        run: ./gradlew test

      # ------------------------
      # 2?? Integration Tests
      # ------------------------
      - name: Run Integration Tests
        run: ./gradlew integrationTest
        continue-on-error: false

      # ------------------------
      # 3?? SonarQube Scan
      # ------------------------
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=payment-service
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}

      # ------------------------
      # 4?? Veracode Security Scan
      # ------------------------
      - name: Veracode Scan
        uses: veracode/veracode-uploadandscan-action@v1
        with:
          appname: "payment-service"
          createprofile: true
          filepath: build/libs/*.jar
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}

  docker-build-deploy:
    needs: build-test-scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker Image
        run: |
          docker build -t payment-service .
          docker tag payment-service:latest 987540641265.dkr.ecr.us-east-1.amazonaws.com/payment-service:latest
          docker push 987540641265.dkr.ecr.us-east-1.amazonaws.com/payment-service:latest

      - name: Deploy to ECS
        run: |
          aws ecs update-service \
            --cluster payment-cluster \
            --service payment-service \
            --force-new-deployment